#These are Global Settings for Residence.
Global:
    # This loads the <language>.yml file in the Residence Language folder
    # All Residence text comes from this file. (NOT DONE YET)
    Language: English
    # Wooden Axe is the default selection tool for Residence.
    # You can change it to another item ID listed here: http://www.minecraftwiki.net/wiki/Data_values
    SelectionToolId: 271
    # This determins which tool you can use to see info on residences, default is String.
    # Simply equip this tool and hit a location inside the residence and it will display the info for it.
    InfoToolId: 287
    # The interval, in milliseconds, between movement checks.
    # Reducing this will increase the load on the server.
    # Increasing this will allow players to move further in movement restricted zones before they are teleported out.
    MoveCheckInterval: 500
    # The default group to use if Permissions fails to attach or your not using Permissions.
    DefaultGroup: default
    # Enable / Disable the Lease System.
    UseLeaseSystem: false
    # The interval, in minutes, between residence lease checks (if leases are enabled).
    LeaseCheckInterval: 10
    # Allows leases to automatically renew so long as the player has the money, if economy is disabled, this setting does nothing.
    LeaseAutoRenew: true
    # Whether or not to use the Permissions system in conjunction with this config.
    EnablePermissions: true
    # Set to true if NOT using Permissions or PermissionsBukkit, or using a really old version of Permissions
    LegacyPermissions: false
    # Enable / Disable Residence's Economy System (iConomy, MineConomy, Essentials, BOSEconomy, and RealEconomy supported).
    EnableEconomy: true
    # Enables or disables the Rent System
    EnableRentSystem: false
    # The interval, in minutes, between residence rent expiration checks (if the rent system is enabled).
    RentCheckInterval: 10
    # Enable or disable residence chat channels.
    ResidenceChatEnable: true
    # Color of residence chat.
    ResidenceChatColor: DARK_PURPLE
    # Whether or not to ignore the usual Permission flags and only allow OPs and groups with 'residence.admin' to change residences.
    AdminOnlyCommands: false
    # Setting this to true makes server OPs admins.
    AdminOPs: true
    # This is the name of the plugin you use for multiworld, if you dont have a multiworld plugin you can safely ignore this.
    # The only thing this does is check to make sure the multiworld plugin is enabled BEFORE Residence, to ensure properly loading residences for other worlds.
    MultiWorldPlugin: Multiverse-Core
    # Setting this to true causes subzones to inherit flags from their parent zones.
    ResidenceFlagsInherit: true
    # This is the residence name filter, that filters out invalid characters.  Google "Java RegEx" or "Java Regular Expressions" for more info on how they work.
    ResidenceNameRegex: '[^a-zA-Z0-9\\-\\_]'
    # Setting this to true sends a message to the console every time Residence does a rent expire check or a lease expire check.
    ShowIntervalMessages: false
    # Experimental - The following settings are lists of block IDs to be used as part of the checks for the "container" and "use" flags when using mods.
    CustomContainers: []
    CustomBothClick: []
    CustomRightClick: []
    # These are default flags applied to all residences from any user group.
    ResidenceDefault:
        build: false
        use: false
        container: false
        pvp: false
        tnt: false
        creeper: false
        flow: false
        piston: false
        ignite: false
        firespread: false
        piston: false
    # These are default flags applied to the residence creator of any group.
    CreatorDefault:
        build: true
        move: true
        use: true
        ignite: true
        container: true   
# These groups correspond to the Permissions groups defined in your '<worldname>.yml'
Groups:
    Default: #group name
       # Information about the Residence zone that the player can define.
       #Uncomment the lines below to mirror this config to other groups.
       #Mirror:
         #- 'group1'
         #- 'group2'
       Residence:
           # The maximum number of Residences a player can have.
           MaxResidences: 3
           # The maximum number of physical areas a residence can have.
           MaxAreasPerResidence: 2
           # The maximum number of blocks a Residence can be, East to West (X).
           MaxEastWest: 16
           # The maximum number of blocks a Residence can be, North to South (Z).
           MaxNorthSouth: 16
           # The maximum number of blocks a Residence can be, High to Low (Y).
           MaxUpDown: 256
           # The lowest altitude this group is allowed to protect.
           MinHeight: 0
           # The highest altitude this group is allowed to protect.
           MaxHeight: 255
            # The maximum recursive depth that subzones can go.
            # A subzone within a subzone within the Residence zone would be a depth of 2.
            # Set to 0 to disable subzones.
           SubzoneDepth: 3
       # Options relating to enter and leave messages on the residence.
       Messaging:
           # Whether or not the player can change the Residence enter and leave messages.
           CanChange: true
           # The default enter message to apply to new Residences created by players in this group.
           # Leaving the message blank will disable it.
           DefaultEnter: Welcome %player to %residence, owned by %owner.
           # The default leave message to apply to new Residences created by players in this group.
           # Leaving the message blank will disable it.
           DefaultLeave: Now leaving %residence.
       # Options relating to the Lease system.
       Lease:
          # The maximum number of days to allow leases.
          MaxDays: 16
          # The number of days to add to the lease following a '/res lease renew' command.
          RenewIncrement: 14
       #Options related to the rent system
       Rent:
           #determines how many residences can be rented by players of this group at once
           MaxRents: 3
           #determines how many residences can be set for rent by players of this group at once
           MaxRentables: 3
       # Options relating to the Residence Economy.
       Economy:
          # The cost, per block, of making a new Residence or adding a area to it.
          BuyCost: 0.05
          # The cost, per block, of renewing a Residence lease (if the lease system is enabled).
          RenewCost: 0.02
       # Flags are checked in the order:
       # 1: Player
       # 2: Group
       # 3: Owner
       # 4: If all others are undefined, reverts to default value (usually true).
       # Flag permissions default to false.
       # These flags settings override the globals.
       Flags:
          # Specifys the flags that are applied at residence creation for players of this group.
          Default:
              #build: true
          # Specifys the flags that are applied at to the creator at residence creation.
          CreatorDefault:
              #build: true
          # Specifys the flags that are applied to other groups for this residence, at creation.
          GroupDefault:
               #default: #group name
                   #build: false

# You can manually specify the group a player is in below, this overrides their permissions group.
GroupAssignments:
     bekvon: default
     player: default

ItemList: #this is where you can create blacklists / whitelists
     DefaultList: #list name is not important, as long as it is unique. Its good to use a descripive name. 
        #type of the list, can be blacklist, whitelist, or ignorelist
        Type: blacklist
        #If you want, you can have this list only apply to one world, otherwise it applys to all worlds
        #World: world
        #You can also have the list apply only to one group, otherwise it applys for all groups
        #Group: default
        #this is the actual list of material names that this list allows or dissallows
        #You can look up the material name by item ID in game by typing /res material <id>
        #Alternativly, you can simply use the item ID in the list, but its less descriptive and harder to see what the list allows or dissallows at a glance
        Items: 
           - 'BEDROCK'
           - 'LAVA'
           - 'WATER'
           - 'STATIONARY_LAVA'
           - 'STATIONARY_WATER'
           - 'MOB_SPAWNER'
# Used to determine which major revision of Residence this config is from, dont change this.
ResidenceVersion: 3