name: Residence
main: com.bekvon.bukkit.residence.ResidenceCommandListener
version: 3.0
description: Cuboid Residence Plugin
authors: [t00thpick1,bekvon,nate302]
softdepend: [Vault,Essentials,RealPlugin,BOSEconomy,iConomy,bPermissions,PermissionsBukkit,Permissions,WorldEdit,My Worlds]
commands:
  res:
    description: Manage Residences
    usage: §c/res ? for more info
  residence:
    description: Manage Residences
    usage: §c/residence ? for more info
  resadmin:
    description: Residence admin functions.
    usage: §c/res ? or /resadmin ? for more info
  resreload:
    description: Reload the entire residence plugin.
    usage: §c/resreload
  rc:
    description: §cChat in current residence channel.
    usage: §c/rc to toggle, or /rc <message>
  resworld:
    description: §cRemoves every residence in a world.
    usage: §c/resworld remove [world]
permissions:
  residence.admin:
    description: Gives you access to /resadmin
    default: op
  residence.create:
    description: Allows you to create residences
    default: op
  residence.select.tool:
    description: Gives you access to select with res tool
    default: op
  residence.select.command:
    description: Allows you to select with residence select commands
    default: op
  residence.teleport:
    description: Gives you access to res tp
    default: op
  residence.messages:
    description: Allows you to edit your res enter/leave messages
    default: op
  residence.unstuck:
    description: Gives you access to /res unstuck
    default: op
  residence.itemlists:
    description: Allows you to create and edit blacklist/ignorelists for your res's
    default: op
  residence.canbuy:
    description: Allows you to buy residences
    default: op
  residence.cansell:
    description: Allows you to sell residences
    default: op
  residence.ignorelimits:
    description: Allows you to ignore max res limits when buying residences
    default: op
